# Generated by Django 5.2.8 on 2025-11-24 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_featured_attribute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='featured_attribute',
            new_name='featured_image',
        ),
    ]
